from aws_eks.source_ip_multiple_403 import AmazonEKSAuditMultiple403 as AmazonEKSAuditMultiple403
from aws_eks.source_ip_multiple_403 import amazon_eks_audit_multiple403_tests as amazon_eks_audit_multiple403_tests
from aws_eks.system_namespace_public_ip import (
    AmazonEKSAuditSystemNamespaceFromPublicIP as AmazonEKSAuditSystemNamespaceFromPublicIP,
)
from aws_eks.system_namespace_public_ip import (
    amazon_eks_audit_system_namespace_from_public_ip_tests as amazon_eks_audit_system_namespace_from_public_ip_tests,
)
