from salesforce.salesforce_admin_login_as_user import SalesforceAdminLoginAsUser as SalesforceAdminLoginAsUser
from salesforce.salesforce_admin_login_as_user import (
    salesforce_admin_login_as_user_tests as salesforce_admin_login_as_user_tests,
)
