from aws_cloudtrail.aws_ami_modified_for_public_access import (
    AWSCloudTrailAMIModifiedForPublicAccess as AWSCloudTrailAMIModifiedForPublicAccess,
)
from aws_cloudtrail.aws_ami_modified_for_public_access import (
    aws_cloud_trail_ami_modified_for_public_access_tests as aws_cloud_trail_ami_modified_for_public_access_tests,
)
from aws_cloudtrail.aws_cloudtrail_account_discovery import (
    AWSCloudTrailAccountDiscovery as AWSCloudTrailAccountDiscovery,
)
from aws_cloudtrail.aws_cloudtrail_account_discovery import (
    aws_cloud_trail_account_discovery_tests as aws_cloud_trail_account_discovery_tests,
)
from aws_cloudtrail.aws_cloudtrail_created import AWSCloudTrailCreated as AWSCloudTrailCreated
from aws_cloudtrail.aws_cloudtrail_created import aws_cloud_trail_created_tests as aws_cloud_trail_created_tests
from aws_cloudtrail.aws_cloudtrail_loginprofilecreatedormodified import (
    AWSCloudTrailLoginProfileCreatedOrModified as AWSCloudTrailLoginProfileCreatedOrModified,
)
from aws_cloudtrail.aws_cloudtrail_loginprofilecreatedormodified import (
    aws_cloud_trail_login_profile_created_or_modified_tests as aws_cloud_trail_login_profile_created_or_modified_tests,
)
from aws_cloudtrail.aws_cloudtrail_password_policy_discovery import (
    AWSCloudTrailPasswordPolicyDiscovery as AWSCloudTrailPasswordPolicyDiscovery,
)
from aws_cloudtrail.aws_cloudtrail_password_policy_discovery import (
    aws_cloud_trail_password_policy_discovery_tests as aws_cloud_trail_password_policy_discovery_tests,
)
from aws_cloudtrail.aws_cloudtrail_stopped import AWSCloudTrailStopped as AWSCloudTrailStopped
from aws_cloudtrail.aws_cloudtrail_stopped import aws_cloud_trail_stopped_tests as aws_cloud_trail_stopped_tests
from aws_cloudtrail.aws_cloudtrail_unsuccessful_mfa_attempt import (
    AWSUnsuccessfulMFAattempt as AWSUnsuccessfulMFAattempt,
)
from aws_cloudtrail.aws_cloudtrail_unsuccessful_mfa_attempt import (
    aws_unsuccessful_mf_aattempt_tests as aws_unsuccessful_mf_aattempt_tests,
)
from aws_cloudtrail.aws_cloudtrail_useraccesskeyauth import (
    AWSCloudTrailUserAccessKeyAuth as AWSCloudTrailUserAccessKeyAuth,
)
from aws_cloudtrail.aws_cloudtrail_useraccesskeyauth import (
    aws_cloud_trail_user_access_key_auth_tests as aws_cloud_trail_user_access_key_auth_tests,
)
from aws_cloudtrail.aws_codebuild_made_public import (
    AWSCloudTrailCodebuildProjectMadePublic as AWSCloudTrailCodebuildProjectMadePublic,
)
from aws_cloudtrail.aws_codebuild_made_public import (
    aws_cloud_trail_codebuild_project_made_public_tests as aws_cloud_trail_codebuild_project_made_public_tests,
)
from aws_cloudtrail.aws_config_service_created import AWSConfigServiceCreated as AWSConfigServiceCreated
from aws_cloudtrail.aws_config_service_created import (
    aws_config_service_created_tests as aws_config_service_created_tests,
)
from aws_cloudtrail.aws_config_service_disabled_deleted import (
    AWSConfigServiceDisabledDeleted as AWSConfigServiceDisabledDeleted,
)
from aws_cloudtrail.aws_config_service_disabled_deleted import (
    aws_config_service_disabled_deleted_tests as aws_config_service_disabled_deleted_tests,
)
from aws_cloudtrail.aws_console_login import AWSConsoleLogin as AWSConsoleLogin
from aws_cloudtrail.aws_console_login_without_mfa import AWSConsoleLoginWithoutMFA as AWSConsoleLoginWithoutMFA
from aws_cloudtrail.aws_console_login_without_mfa import (
    aws_console_login_without_mfa_tests as aws_console_login_without_mfa_tests,
)
from aws_cloudtrail.aws_console_login_without_saml import AWSConsoleLoginWithoutSAML as AWSConsoleLoginWithoutSAML
from aws_cloudtrail.aws_console_login_without_saml import (
    aws_console_login_without_saml_tests as aws_console_login_without_saml_tests,
)
from aws_cloudtrail.aws_console_root_login import AWSConsoleRootLogin as AWSConsoleRootLogin
from aws_cloudtrail.aws_console_root_login import aws_console_root_login_tests as aws_console_root_login_tests
from aws_cloudtrail.aws_console_root_login_failed import AWSConsoleRootLoginFailed as AWSConsoleRootLoginFailed
from aws_cloudtrail.aws_console_root_login_failed import (
    aws_console_root_login_failed_tests as aws_console_root_login_failed_tests,
)
from aws_cloudtrail.aws_console_signin import AWSConsoleSignIn as AWSConsoleSignIn
from aws_cloudtrail.aws_console_signin import aws_console_sign_in_tests as aws_console_sign_in_tests
from aws_cloudtrail.aws_ec2_ebs_encryption_disabled import AWSEC2EBSEncryptionDisabled as AWSEC2EBSEncryptionDisabled
from aws_cloudtrail.aws_ec2_ebs_encryption_disabled import (
    awsec2_ebs_encryption_disabled_tests as awsec2_ebs_encryption_disabled_tests,
)
from aws_cloudtrail.aws_ec2_gateway_modified import AWSEC2GatewayModified as AWSEC2GatewayModified
from aws_cloudtrail.aws_ec2_gateway_modified import awsec2_gateway_modified_tests as awsec2_gateway_modified_tests
from aws_cloudtrail.aws_ec2_manual_security_group_changes import (
    AWSEC2ManualSecurityGroupChange as AWSEC2ManualSecurityGroupChange,
)
from aws_cloudtrail.aws_ec2_manual_security_group_changes import (
    awsec2_manual_security_group_change_tests as awsec2_manual_security_group_change_tests,
)
from aws_cloudtrail.aws_ec2_monitoring import AWSEC2Monitoring as AWSEC2Monitoring
from aws_cloudtrail.aws_ec2_monitoring import awsec2_monitoring_tests as awsec2_monitoring_tests
from aws_cloudtrail.aws_ec2_network_acl_modified import AWSEC2NetworkACLModified as AWSEC2NetworkACLModified
from aws_cloudtrail.aws_ec2_network_acl_modified import (
    awsec2_network_acl_modified_tests as awsec2_network_acl_modified_tests,
)
from aws_cloudtrail.aws_ec2_route_table_modified import AWSEC2RouteTableModified as AWSEC2RouteTableModified
from aws_cloudtrail.aws_ec2_route_table_modified import (
    awsec2_route_table_modified_tests as awsec2_route_table_modified_tests,
)
from aws_cloudtrail.aws_ec2_security_group_modified import AWSEC2SecurityGroupModified as AWSEC2SecurityGroupModified
from aws_cloudtrail.aws_ec2_security_group_modified import (
    awsec2_security_group_modified_tests as awsec2_security_group_modified_tests,
)
from aws_cloudtrail.aws_ec2_startup_script_change import AWSEC2StartupScriptChange as AWSEC2StartupScriptChange
from aws_cloudtrail.aws_ec2_startup_script_change import (
    awsec2_startup_script_change_tests as awsec2_startup_script_change_tests,
)
from aws_cloudtrail.aws_ec2_stopinstances import AWSEC2StopInstances as AWSEC2StopInstances
from aws_cloudtrail.aws_ec2_stopinstances import awsec2_stop_instances_tests as awsec2_stop_instances_tests
from aws_cloudtrail.aws_ec2_traffic_mirroring import AWSEC2TrafficMirroring as AWSEC2TrafficMirroring
from aws_cloudtrail.aws_ec2_traffic_mirroring import awsec2_traffic_mirroring_tests as awsec2_traffic_mirroring_tests
from aws_cloudtrail.aws_ec2_vpc_modified import AWSEC2VPCModified as AWSEC2VPCModified
from aws_cloudtrail.aws_ec2_vpc_modified import awsec2_vpc_modified_tests as awsec2_vpc_modified_tests
from aws_cloudtrail.aws_ec2_vulnerable_xz_image_launched import (
    AWSEC2VulnerableXZImageLaunched as AWSEC2VulnerableXZImageLaunched,
)
from aws_cloudtrail.aws_ec2_vulnerable_xz_image_launched import (
    awsec2_vulnerable_xz_image_launched_tests as awsec2_vulnerable_xz_image_launched_tests,
)
from aws_cloudtrail.aws_ecr_crud import AWSECRCRUD as AWSECRCRUD
from aws_cloudtrail.aws_ecr_crud import awsecrcrud_tests as awsecrcrud_tests
from aws_cloudtrail.aws_ecr_events import AWSECREVENTS as AWSECREVENTS
from aws_cloudtrail.aws_ecr_events import awsecrevents_tests as awsecrevents_tests
from aws_cloudtrail.aws_iam_anything_changed import AWSCloudTrailIAMAnythingChanged as AWSCloudTrailIAMAnythingChanged
from aws_cloudtrail.aws_iam_anything_changed import (
    aws_cloud_trail_iam_anything_changed_tests as aws_cloud_trail_iam_anything_changed_tests,
)
from aws_cloudtrail.aws_iam_assume_role_blocklist_ignored import (
    AWSCloudTrailIAMAssumeRoleBlacklistIgnored as AWSCloudTrailIAMAssumeRoleBlacklistIgnored,
)
from aws_cloudtrail.aws_iam_assume_role_blocklist_ignored import (
    aws_cloud_trail_iam_assume_role_blacklist_ignored_tests as aws_cloud_trail_iam_assume_role_blacklist_ignored_tests,
)
from aws_cloudtrail.aws_iam_compromised_key_quarantine import (
    AWSCloudTrailIAMCompromisedKeyQuarantine as AWSCloudTrailIAMCompromisedKeyQuarantine,
)
from aws_cloudtrail.aws_iam_compromised_key_quarantine import (
    aws_cloud_trail_iam_compromised_key_quarantine_tests as aws_cloud_trail_iam_compromised_key_quarantine_tests,
)
from aws_cloudtrail.aws_iam_entity_created_without_cloudformation import (
    AWSCloudTrailIAMEntityCreatedWithoutCloudFormation as AWSCloudTrailIAMEntityCreatedWithoutCloudFormation,
)
from aws_cloudtrail.aws_iam_entity_created_without_cloudformation import (
    aws_cloud_trail_iam_entity_created_without_cloud_formation_tests as aws_cloud_trail_iam_entity_created_without_cloud_formation_tests,
)
from aws_cloudtrail.aws_iam_group_read_only_events import AWSIAMGroupReadOnlyEvents as AWSIAMGroupReadOnlyEvents
from aws_cloudtrail.aws_iam_group_read_only_events import (
    awsiam_group_read_only_events_tests as awsiam_group_read_only_events_tests,
)
from aws_cloudtrail.aws_iam_policy_modified import AWSIAMPolicyModified as AWSIAMPolicyModified
from aws_cloudtrail.aws_iam_policy_modified import awsiam_policy_modified_tests as awsiam_policy_modified_tests
from aws_cloudtrail.aws_iam_user_key_created import AWSIAMBackdoorUserKeys as AWSIAMBackdoorUserKeys
from aws_cloudtrail.aws_iam_user_key_created import awsiam_backdoor_user_keys_tests as awsiam_backdoor_user_keys_tests
from aws_cloudtrail.aws_iam_user_recon_denied import AWSIAMUserReconAccessDenied as AWSIAMUserReconAccessDenied
from aws_cloudtrail.aws_iam_user_recon_denied import (
    awsiam_user_recon_access_denied_tests as awsiam_user_recon_access_denied_tests,
)
from aws_cloudtrail.aws_ipset_modified import AWSIPSetModified as AWSIPSetModified
from aws_cloudtrail.aws_ipset_modified import awsip_set_modified_tests as awsip_set_modified_tests
from aws_cloudtrail.aws_key_compromised import AWSIAMAccessKeyCompromised as AWSIAMAccessKeyCompromised
from aws_cloudtrail.aws_key_compromised import (
    awsiam_access_key_compromised_tests as awsiam_access_key_compromised_tests,
)
from aws_cloudtrail.aws_kms_cmk_loss import AWSKMSCustomerManagedKeyLoss as AWSKMSCustomerManagedKeyLoss
from aws_cloudtrail.aws_kms_cmk_loss import (
    awskms_customer_managed_key_loss_tests as awskms_customer_managed_key_loss_tests,
)
from aws_cloudtrail.aws_lambda_crud import AWSLAMBDACRUD as AWSLAMBDACRUD
from aws_cloudtrail.aws_lambda_crud import awslambdacrud_tests as awslambdacrud_tests
from aws_cloudtrail.aws_macie_evasion import AWSMacieEvasion as AWSMacieEvasion
from aws_cloudtrail.aws_macie_evasion import aws_macie_evasion_tests as aws_macie_evasion_tests
from aws_cloudtrail.aws_modify_cloud_compute_infrastructure import (
    AWSModifyCloudComputeInfrastructure as AWSModifyCloudComputeInfrastructure,
)
from aws_cloudtrail.aws_modify_cloud_compute_infrastructure import (
    aws_modify_cloud_compute_infrastructure_tests as aws_modify_cloud_compute_infrastructure_tests,
)
from aws_cloudtrail.aws_network_acl_permissive_entry import (
    AWSCloudTrailNetworkACLPermissiveEntry as AWSCloudTrailNetworkACLPermissiveEntry,
)
from aws_cloudtrail.aws_network_acl_permissive_entry import (
    aws_cloud_trail_network_acl_permissive_entry_tests as aws_cloud_trail_network_acl_permissive_entry_tests,
)
from aws_cloudtrail.aws_rds_manual_snapshot_created import AWSRDSManualSnapshotCreated as AWSRDSManualSnapshotCreated
from aws_cloudtrail.aws_rds_manual_snapshot_created import (
    awsrds_manual_snapshot_created_tests as awsrds_manual_snapshot_created_tests,
)
from aws_cloudtrail.aws_rds_master_pass_updated import AWSRDSMasterPasswordUpdated as AWSRDSMasterPasswordUpdated
from aws_cloudtrail.aws_rds_master_pass_updated import (
    awsrds_master_password_updated_tests as awsrds_master_password_updated_tests,
)
from aws_cloudtrail.aws_rds_publicrestore import AWSRDSPublicRestore as AWSRDSPublicRestore
from aws_cloudtrail.aws_rds_publicrestore import awsrds_public_restore_tests as awsrds_public_restore_tests
from aws_cloudtrail.aws_rds_snapshot_shared import AWSRDSSnapshotShared as AWSRDSSnapshotShared
from aws_cloudtrail.aws_rds_snapshot_shared import awsrds_snapshot_shared_tests as awsrds_snapshot_shared_tests
from aws_cloudtrail.aws_resource_made_public import AWSCloudTrailResourceMadePublic as AWSCloudTrailResourceMadePublic
from aws_cloudtrail.aws_resource_made_public import (
    aws_cloud_trail_resource_made_public_tests as aws_cloud_trail_resource_made_public_tests,
)
from aws_cloudtrail.aws_root_access_key_created import (
    AWSCloudTrailRootAccessKeyCreated as AWSCloudTrailRootAccessKeyCreated,
)
from aws_cloudtrail.aws_root_access_key_created import (
    aws_cloud_trail_root_access_key_created_tests as aws_cloud_trail_root_access_key_created_tests,
)
from aws_cloudtrail.aws_root_activity import AWSRootActivity as AWSRootActivity
from aws_cloudtrail.aws_root_activity import aws_root_activity_tests as aws_root_activity_tests
from aws_cloudtrail.aws_root_password_changed import (
    AWSCloudTrailRootPasswordChanged as AWSCloudTrailRootPasswordChanged,
)
from aws_cloudtrail.aws_root_password_changed import (
    aws_cloud_trail_root_password_changed_tests as aws_cloud_trail_root_password_changed_tests,
)
from aws_cloudtrail.aws_s3_bucket_deleted import AWSS3BucketDeleted as AWSS3BucketDeleted
from aws_cloudtrail.aws_s3_bucket_deleted import awss3_bucket_deleted_tests as awss3_bucket_deleted_tests
from aws_cloudtrail.aws_s3_bucket_policy_modified import AWSS3BucketPolicyModified as AWSS3BucketPolicyModified
from aws_cloudtrail.aws_s3_bucket_policy_modified import (
    awss3_bucket_policy_modified_tests as awss3_bucket_policy_modified_tests,
)
from aws_cloudtrail.aws_saml_activity import AWSSuspiciousSAMLActivity as AWSSuspiciousSAMLActivity
from aws_cloudtrail.aws_saml_activity import aws_suspicious_saml_activity_tests as aws_suspicious_saml_activity_tests
from aws_cloudtrail.aws_security_configuration_change import (
    AWSCloudTrailSecurityConfigurationChange as AWSCloudTrailSecurityConfigurationChange,
)
from aws_cloudtrail.aws_security_configuration_change import (
    aws_cloud_trail_security_configuration_change_tests as aws_cloud_trail_security_configuration_change_tests,
)
from aws_cloudtrail.aws_securityhub_finding_evasion import AWSSecurityHubFindingEvasion as AWSSecurityHubFindingEvasion
from aws_cloudtrail.aws_securityhub_finding_evasion import (
    aws_security_hub_finding_evasion_tests as aws_security_hub_finding_evasion_tests,
)
from aws_cloudtrail.aws_snapshot_made_public import AWSCloudTrailSnapshotMadePublic as AWSCloudTrailSnapshotMadePublic
from aws_cloudtrail.aws_snapshot_made_public import (
    aws_cloud_trail_snapshot_made_public_tests as aws_cloud_trail_snapshot_made_public_tests,
)
from aws_cloudtrail.aws_software_discovery import AWSSoftwareDiscovery as AWSSoftwareDiscovery
from aws_cloudtrail.aws_software_discovery import aws_software_discovery_tests as aws_software_discovery_tests
from aws_cloudtrail.aws_unauthorized_api_call import (
    AWSCloudTrailUnauthorizedAPICall as AWSCloudTrailUnauthorizedAPICall,
)
from aws_cloudtrail.aws_unauthorized_api_call import (
    aws_cloud_trail_unauthorized_api_call_tests as aws_cloud_trail_unauthorized_api_call_tests,
)
from aws_cloudtrail.aws_unused_region import AWSUnusedRegion as AWSUnusedRegion
from aws_cloudtrail.aws_unused_region import aws_unused_region_tests as aws_unused_region_tests
from aws_cloudtrail.aws_update_credentials import AWSIAMCredentialsUpdated as AWSIAMCredentialsUpdated
from aws_cloudtrail.aws_update_credentials import awsiam_credentials_updated_tests as awsiam_credentials_updated_tests
from aws_cloudtrail.aws_user_login_profile_modified import AWSUserLoginProfileModified as AWSUserLoginProfileModified
from aws_cloudtrail.aws_user_login_profile_modified import (
    aws_user_login_profile_modified_tests as aws_user_login_profile_modified_tests,
)
from aws_cloudtrail.aws_waf_disassociation import AWSWAFDisassociation as AWSWAFDisassociation
from aws_cloudtrail.aws_waf_disassociation import awswaf_disassociation_tests as awswaf_disassociation_tests
from aws_cloudtrail.retrieve_sso_access_token import RetrieveSSOaccesstoken as RetrieveSSOaccesstoken
from aws_cloudtrail.retrieve_sso_access_token import retrieve_ss_oaccesstoken_tests as retrieve_ss_oaccesstoken_tests
from aws_cloudtrail.role_assumed_by_aws_service import RoleAssumedbyAWSService as RoleAssumedbyAWSService
from aws_cloudtrail.role_assumed_by_aws_service import (
    role_assumedby_aws_service_tests as role_assumedby_aws_service_tests,
)
from aws_cloudtrail.role_assumed_by_user import RoleAssumedbyUser as RoleAssumedbyUser
from aws_cloudtrail.role_assumed_by_user import role_assumedby_user_tests as role_assumedby_user_tests
from aws_cloudtrail.signin_with_aws_cli_prompt import SigninwithAWSCLIprompt as SigninwithAWSCLIprompt
from aws_cloudtrail.signin_with_aws_cli_prompt import signinwith_awscl_iprompt_tests as signinwith_awscl_iprompt_tests
