from gcp_http_lb.gcp_access_attempts_violating_iap_access_controls import (
    GCPAccessAttemptsViolatingIAPAccessControls as GCPAccessAttemptsViolatingIAPAccessControls,
)
from gcp_http_lb.gcp_access_attempts_violating_iap_access_controls import (
    gcp_access_attempts_violating_iap_access_controls_tests as gcp_access_attempts_violating_iap_access_controls_tests,
)
