from netskope.netskope_admin_logged_out import (
    NetskopeAdminLoggedOutLoginFailures as NetskopeAdminLoggedOutLoginFailures,
)
from netskope.netskope_admin_logged_out import (
    netskope_admin_logged_out_login_failures_tests as netskope_admin_logged_out_login_failures_tests,
)
from netskope.netskope_admin_user_change import NetskopeAdminUserChange as NetskopeAdminUserChange
from netskope.netskope_admin_user_change import netskope_admin_user_change_tests as netskope_admin_user_change_tests
from netskope.netskope_many_deletes import NetskopeManyDeletes as NetskopeManyDeletes
from netskope.netskope_many_deletes import netskope_many_deletes_tests as netskope_many_deletes_tests
from netskope.netskope_personnel_action import NetskopeNetskopePersonnelActivity as NetskopeNetskopePersonnelActivity
from netskope.netskope_personnel_action import (
    netskope_netskope_personnel_activity_tests as netskope_netskope_personnel_activity_tests,
)
from netskope.netskope_unauthorized_api_calls import NetskopeUnauthorizedAPICalls as NetskopeUnauthorizedAPICalls
from netskope.netskope_unauthorized_api_calls import (
    netskope_unauthorized_api_calls_tests as netskope_unauthorized_api_calls_tests,
)
