from standard.admin_assigned import StandardAdminRoleAssigned as StandardAdminRoleAssigned
from standard.admin_assigned import standard_admin_role_assigned_tests as standard_admin_role_assigned_tests
from standard.brute_force_by_ip import StandardBruteForceByIP as StandardBruteForceByIP
from standard.brute_force_by_ip import standard_brute_force_by_ip_tests as standard_brute_force_by_ip_tests
from standard.impossible_travel_login import StandardImpossibleTravelLogin as StandardImpossibleTravelLogin
from standard.impossible_travel_login import (
    standard_impossible_travel_login_tests as standard_impossible_travel_login_tests,
)
from standard.malicious_sso_dns_lookup import StandardMaliciousSSODNSLookup as StandardMaliciousSSODNSLookup
from standard.malicious_sso_dns_lookup import (
    standard_malicious_ssodns_lookup_tests as standard_malicious_ssodns_lookup_tests,
)
from standard.mfa_disabled import StandardMFADisabled as StandardMFADisabled
from standard.mfa_disabled import standard_mfa_disabled_tests as standard_mfa_disabled_tests
from standard.standard_dns_base64 import StandardDNSBase64 as StandardDNSBase64
from standard.standard_dns_base64 import standard_dns_base64_tests as standard_dns_base64_tests
