from onelogin.onelogin_active_login_activity import OneLoginActiveLoginActivity as OneLoginActiveLoginActivity
from onelogin.onelogin_active_login_activity import (
    one_login_active_login_activity_tests as one_login_active_login_activity_tests,
)
from onelogin.onelogin_high_risk_failed_login import OneLoginHighRiskFailedLogin as OneLoginHighRiskFailedLogin
from onelogin.onelogin_high_risk_failed_login import (
    one_login_high_risk_failed_login_tests as one_login_high_risk_failed_login_tests,
)
from onelogin.onelogin_high_risk_login import OneLoginHighRiskLogin as OneLoginHighRiskLogin
from onelogin.onelogin_high_risk_login import one_login_high_risk_login_tests as one_login_high_risk_login_tests
from onelogin.onelogin_password_accessed import OneLoginPasswordAccess as OneLoginPasswordAccess
from onelogin.onelogin_password_accessed import one_login_password_access_tests as one_login_password_access_tests
from onelogin.onelogin_password_changed import OneLoginPasswordChanged as OneLoginPasswordChanged
from onelogin.onelogin_password_changed import one_login_password_changed_tests as one_login_password_changed_tests
from onelogin.onelogin_remove_authentication_factor import OneLoginAuthFactorRemoved as OneLoginAuthFactorRemoved
from onelogin.onelogin_remove_authentication_factor import (
    one_login_auth_factor_removed_tests as one_login_auth_factor_removed_tests,
)
from onelogin.onelogin_threshold_accounts_deleted import (
    OneLoginThresholdAccountsDeleted as OneLoginThresholdAccountsDeleted,
)
from onelogin.onelogin_threshold_accounts_deleted import (
    one_login_threshold_accounts_deleted_tests as one_login_threshold_accounts_deleted_tests,
)
from onelogin.onelogin_threshold_accounts_modified import (
    OneLoginThresholdAccountsModified as OneLoginThresholdAccountsModified,
)
from onelogin.onelogin_threshold_accounts_modified import (
    one_login_threshold_accounts_modified_tests as one_login_threshold_accounts_modified_tests,
)
from onelogin.onelogin_unauthorized_access import OneLoginUnauthorizedAccess as OneLoginUnauthorizedAccess
from onelogin.onelogin_unauthorized_access import (
    one_login_unauthorized_access_tests as one_login_unauthorized_access_tests,
)
from onelogin.onelogin_user_account_locked import OneLoginUserAccountLocked as OneLoginUserAccountLocked
from onelogin.onelogin_user_account_locked import (
    one_login_user_account_locked_tests as one_login_user_account_locked_tests,
)
from onelogin.onelogin_user_assumed import OneLoginUserAssumption as OneLoginUserAssumption
from onelogin.onelogin_user_assumed import one_login_user_assumption_tests as one_login_user_assumption_tests
