from box.box_access_granted import BoxAccessGranted as BoxAccessGranted
from box.box_access_granted import box_access_granted_tests as box_access_granted_tests
from box.box_anomalous_download import BoxShieldAnomalousDownload as BoxShieldAnomalousDownload
from box.box_anomalous_download import box_shield_anomalous_download_tests as box_shield_anomalous_download_tests
from box.box_event_triggered_externally import BoxEventTriggeredExternally as BoxEventTriggeredExternally
from box.box_event_triggered_externally import (
    box_event_triggered_externally_tests as box_event_triggered_externally_tests,
)
from box.box_item_shared_externally import BoxItemSharedExternally as BoxItemSharedExternally
from box.box_item_shared_externally import box_item_shared_externally_tests as box_item_shared_externally_tests
from box.box_malicious_content import BoxMaliciousContent as BoxMaliciousContent
from box.box_malicious_content import box_malicious_content_tests as box_malicious_content_tests
from box.box_new_login import BoxNewLogin as BoxNewLogin
from box.box_new_login import box_new_login_tests as box_new_login_tests
from box.box_policy_violation import BoxContentWorkflowPolicyViolation as BoxContentWorkflowPolicyViolation
from box.box_policy_violation import (
    box_content_workflow_policy_violation_tests as box_content_workflow_policy_violation_tests,
)
from box.box_suspicious_login_or_session import BoxShieldSuspiciousAlert as BoxShieldSuspiciousAlert
from box.box_suspicious_login_or_session import box_shield_suspicious_alert_tests as box_shield_suspicious_alert_tests
from box.box_untrusted_device import BoxUntrustedDevice as BoxUntrustedDevice
from box.box_untrusted_device import box_untrusted_device_tests as box_untrusted_device_tests
from box.box_user_downloads import BoxLargeNumberDownloads as BoxLargeNumberDownloads
from box.box_user_downloads import box_large_number_downloads_tests as box_large_number_downloads_tests
from box.box_user_permission_updates import BoxLargeNumberPermissionUpdates as BoxLargeNumberPermissionUpdates
from box.box_user_permission_updates import (
    box_large_number_permission_updates_tests as box_large_number_permission_updates_tests,
)
