from cisco_umbrella_dns.domain_blocked import CiscoUmbrellaDNSBlocked as CiscoUmbrellaDNSBlocked
from cisco_umbrella_dns.domain_blocked import cisco_umbrella_dns_blocked_tests as cisco_umbrella_dns_blocked_tests
from cisco_umbrella_dns.fuzzy_matching_domains import CiscoUmbrellaDNSFuzzyMatching as CiscoUmbrellaDNSFuzzyMatching
from cisco_umbrella_dns.suspicious_domains import CiscoUmbrellaDNSSuspicious as CiscoUmbrellaDNSSuspicious
from cisco_umbrella_dns.suspicious_domains import (
    cisco_umbrella_dns_suspicious_tests as cisco_umbrella_dns_suspicious_tests,
)
