from indicator_creation.new_aws_account_logging import StandardNewAWSAccountCreated as StandardNewAWSAccountCreated
from indicator_creation.new_aws_account_logging import (
    standard_new_aws_account_created_tests as standard_new_aws_account_created_tests,
)
from indicator_creation.new_user_account_logging import StandardNewUserAccountCreated as StandardNewUserAccountCreated
from indicator_creation.new_user_account_logging import (
    standard_new_user_account_created_tests as standard_new_user_account_created_tests,
)
