from mongodb.mongodb_2fa_disabled import MongoDB2FADisabled as MongoDB2FADisabled
from mongodb.mongodb_2fa_disabled import mongo_db2_fa_disabled_tests as mongo_db2_fa_disabled_tests
from mongodb.mongodb_access_allowed_from_anywhere import (
    MongoDBAccessAllowedFromAnywhere as MongoDBAccessAllowedFromAnywhere,
)
from mongodb.mongodb_access_allowed_from_anywhere import (
    mongo_db_access_allowed_from_anywhere_tests as mongo_db_access_allowed_from_anywhere_tests,
)
from mongodb.mongodb_alerting_disabled import MongoDBAlertingDisabledOrDeleted as MongoDBAlertingDisabledOrDeleted
from mongodb.mongodb_alerting_disabled import (
    mongo_db_alerting_disabled_or_deleted_tests as mongo_db_alerting_disabled_or_deleted_tests,
)
from mongodb.mongodb_atlas_api_key_created import MongoDBAtlasApiKeyCreated as MongoDBAtlasApiKeyCreated
from mongodb.mongodb_atlas_api_key_created import (
    mongo_db_atlas_api_key_created_tests as mongo_db_atlas_api_key_created_tests,
)
from mongodb.mongodb_external_user_invited import MongoDBExternalUserInvited as MongoDBExternalUserInvited
from mongodb.mongodb_external_user_invited import (
    mongo_db_external_user_invited_tests as mongo_db_external_user_invited_tests,
)
from mongodb.mongodb_external_user_invited_no_config import (
    MongoDBExternalUserInvitedNoConfig as MongoDBExternalUserInvitedNoConfig,
)
from mongodb.mongodb_external_user_invited_no_config import (
    mongo_db_external_user_invited_no_config_tests as mongo_db_external_user_invited_no_config_tests,
)
from mongodb.mongodb_identity_provider_activity import (
    MongoDBIdentityProviderActivity as MongoDBIdentityProviderActivity,
)
from mongodb.mongodb_identity_provider_activity import (
    mongo_db_identity_provider_activity_tests as mongo_db_identity_provider_activity_tests,
)
from mongodb.mongodb_logging_toggled import MongoDBLoggingToggled as MongoDBLoggingToggled
from mongodb.mongodb_logging_toggled import mongo_db_logging_toggled_tests as mongo_db_logging_toggled_tests
from mongodb.mongodb_org_membership_restriction_disabled import (
    MongoDBorgMembershipRestrictionDisabled as MongoDBorgMembershipRestrictionDisabled,
)
from mongodb.mongodb_org_membership_restriction_disabled import (
    mongo_d_borg_membership_restriction_disabled_tests as mongo_d_borg_membership_restriction_disabled_tests,
)
from mongodb.mongodb_user_created_or_deleted import MongoDBUserCreatedOrDeleted as MongoDBUserCreatedOrDeleted
from mongodb.mongodb_user_created_or_deleted import (
    mongo_db_user_created_or_deleted_tests as mongo_db_user_created_or_deleted_tests,
)
from mongodb.mongodb_user_roles_changed import MongoDBUserRolesChanged as MongoDBUserRolesChanged
from mongodb.mongodb_user_roles_changed import mongo_db_user_roles_changed_tests as mongo_db_user_roles_changed_tests
