from gsuite_activityevent.google_workspace_admin_custom_role import (
    GoogleWorkspaceAdminCustomRole as GoogleWorkspaceAdminCustomRole,
)
from gsuite_activityevent.google_workspace_admin_custom_role import (
    google_workspace_admin_custom_role_tests as google_workspace_admin_custom_role_tests,
)
from gsuite_activityevent.google_workspace_advanced_protection_program import (
    GoogleWorkspaceAdvancedProtectionProgram as GoogleWorkspaceAdvancedProtectionProgram,
)
from gsuite_activityevent.google_workspace_advanced_protection_program import (
    google_workspace_advanced_protection_program_tests as google_workspace_advanced_protection_program_tests,
)
from gsuite_activityevent.google_workspace_apps_marketplace_allowlist import (
    GoogleWorkspaceAppsMarketplaceAllowlist as GoogleWorkspaceAppsMarketplaceAllowlist,
)
from gsuite_activityevent.google_workspace_apps_marketplace_allowlist import (
    google_workspace_apps_marketplace_allowlist_tests as google_workspace_apps_marketplace_allowlist_tests,
)
from gsuite_activityevent.google_workspace_apps_marketplace_new_domain_application import (
    GoogleWorkspaceAppsMarketplaceNewDomainApplication as GoogleWorkspaceAppsMarketplaceNewDomainApplication,
)
from gsuite_activityevent.google_workspace_apps_marketplace_new_domain_application import (
    google_workspace_apps_marketplace_new_domain_application_tests as google_workspace_apps_marketplace_new_domain_application_tests,
)
from gsuite_activityevent.google_workspace_apps_new_mobile_app_installed import (
    GoogleWorkspaceAppsNewMobileAppInstalled as GoogleWorkspaceAppsNewMobileAppInstalled,
)
from gsuite_activityevent.google_workspace_apps_new_mobile_app_installed import (
    google_workspace_apps_new_mobile_app_installed_tests as google_workspace_apps_new_mobile_app_installed_tests,
)
from gsuite_activityevent.gsuite_advanced_protection import GSuiteAdvancedProtection as GSuiteAdvancedProtection
from gsuite_activityevent.gsuite_advanced_protection import (
    g_suite_advanced_protection_tests as g_suite_advanced_protection_tests,
)
from gsuite_activityevent.gsuite_calendar_made_public import GSuiteCalendarMadePublic as GSuiteCalendarMadePublic
from gsuite_activityevent.gsuite_calendar_made_public import (
    g_suite_calendar_made_public_tests as g_suite_calendar_made_public_tests,
)
from gsuite_activityevent.gsuite_doc_ownership_transfer import GSuiteDocOwnershipTransfer as GSuiteDocOwnershipTransfer
from gsuite_activityevent.gsuite_doc_ownership_transfer import (
    g_suite_doc_ownership_transfer_tests as g_suite_doc_ownership_transfer_tests,
)
from gsuite_activityevent.gsuite_external_forwarding import GSuiteExternalMailForwarding as GSuiteExternalMailForwarding
from gsuite_activityevent.gsuite_external_forwarding import (
    g_suite_external_mail_forwarding_tests as g_suite_external_mail_forwarding_tests,
)
from gsuite_activityevent.gsuite_google_access import GSuiteGoogleAccess as GSuiteGoogleAccess
from gsuite_activityevent.gsuite_google_access import g_suite_google_access_tests as g_suite_google_access_tests
from gsuite_activityevent.gsuite_gov_attack import GSuiteGovernmentBackedAttack as GSuiteGovernmentBackedAttack
from gsuite_activityevent.gsuite_gov_attack import (
    g_suite_government_backed_attack_tests as g_suite_government_backed_attack_tests,
)
from gsuite_activityevent.gsuite_group_banned_user import GSuiteGroupBannedUser as GSuiteGroupBannedUser
from gsuite_activityevent.gsuite_group_banned_user import (
    g_suite_group_banned_user_tests as g_suite_group_banned_user_tests,
)
from gsuite_activityevent.gsuite_leaked_password import GSuiteLeakedPassword as GSuiteLeakedPassword
from gsuite_activityevent.gsuite_leaked_password import g_suite_leaked_password_tests as g_suite_leaked_password_tests
from gsuite_activityevent.gsuite_login_type import GSuiteLoginType as GSuiteLoginType
from gsuite_activityevent.gsuite_login_type import g_suite_login_type_tests as g_suite_login_type_tests
from gsuite_activityevent.gsuite_mobile_device_compromise import GSuiteDeviceCompromise as GSuiteDeviceCompromise
from gsuite_activityevent.gsuite_mobile_device_compromise import (
    g_suite_device_compromise_tests as g_suite_device_compromise_tests,
)
from gsuite_activityevent.gsuite_mobile_device_screen_unlock_fail import (
    GSuiteDeviceUnlockFailure as GSuiteDeviceUnlockFailure,
)
from gsuite_activityevent.gsuite_mobile_device_screen_unlock_fail import (
    g_suite_device_unlock_failure_tests as g_suite_device_unlock_failure_tests,
)
from gsuite_activityevent.gsuite_mobile_device_suspicious_activity import (
    GSuiteDeviceSuspiciousActivity as GSuiteDeviceSuspiciousActivity,
)
from gsuite_activityevent.gsuite_mobile_device_suspicious_activity import (
    g_suite_device_suspicious_activity_tests as g_suite_device_suspicious_activity_tests,
)
from gsuite_activityevent.gsuite_passthrough_rule import GSuiteRule as GSuiteRule
from gsuite_activityevent.gsuite_passthrough_rule import g_suite_rule_tests as g_suite_rule_tests
from gsuite_activityevent.gsuite_suspicious_logins import GSuiteSuspiciousLogins as GSuiteSuspiciousLogins
from gsuite_activityevent.gsuite_suspicious_logins import (
    g_suite_suspicious_logins_tests as g_suite_suspicious_logins_tests,
)
from gsuite_activityevent.gsuite_two_step_verification import GSuiteTwoStepVerification as GSuiteTwoStepVerification
from gsuite_activityevent.gsuite_two_step_verification import (
    g_suite_two_step_verification_tests as g_suite_two_step_verification_tests,
)
from gsuite_activityevent.gsuite_user_suspended import GSuiteUserSuspended as GSuiteUserSuspended
from gsuite_activityevent.gsuite_user_suspended import g_suite_user_suspended_tests as g_suite_user_suspended_tests
from gsuite_activityevent.gsuite_workspace_calendar_external_sharing import (
    GSuiteWorkspaceCalendarExternalSharingSetting as GSuiteWorkspaceCalendarExternalSharingSetting,
)
from gsuite_activityevent.gsuite_workspace_calendar_external_sharing import (
    g_suite_workspace_calendar_external_sharing_setting_tests as g_suite_workspace_calendar_external_sharing_setting_tests,
)
from gsuite_activityevent.gsuite_workspace_data_export_created import (
    GSuiteWorkspaceDataExportCreated as GSuiteWorkspaceDataExportCreated,
)
from gsuite_activityevent.gsuite_workspace_data_export_created import (
    g_suite_workspace_data_export_created_tests as g_suite_workspace_data_export_created_tests,
)
from gsuite_activityevent.gsuite_workspace_gmail_default_routing_rule import (
    GSuiteWorkspaceGmailDefaultRoutingRuleModified as GSuiteWorkspaceGmailDefaultRoutingRuleModified,
)
from gsuite_activityevent.gsuite_workspace_gmail_default_routing_rule import (
    g_suite_workspace_gmail_default_routing_rule_modified_tests as g_suite_workspace_gmail_default_routing_rule_modified_tests,
)
from gsuite_activityevent.gsuite_workspace_gmail_enhanced_predelivery_scanning import (
    GSuiteWorkspaceGmailPredeliveryScanningDisabled as GSuiteWorkspaceGmailPredeliveryScanningDisabled,
)
from gsuite_activityevent.gsuite_workspace_gmail_enhanced_predelivery_scanning import (
    g_suite_workspace_gmail_predelivery_scanning_disabled_tests as g_suite_workspace_gmail_predelivery_scanning_disabled_tests,
)
from gsuite_activityevent.gsuite_workspace_gmail_security_sandbox_disabled import (
    GSuiteWorkspaceGmailSecuritySandboxDisabled as GSuiteWorkspaceGmailSecuritySandboxDisabled,
)
from gsuite_activityevent.gsuite_workspace_gmail_security_sandbox_disabled import (
    g_suite_workspace_gmail_security_sandbox_disabled_tests as g_suite_workspace_gmail_security_sandbox_disabled_tests,
)
from gsuite_activityevent.gsuite_workspace_password_enforce_strong_disabled import (
    GSuiteWorkspacePasswordEnforceStrongDisabled as GSuiteWorkspacePasswordEnforceStrongDisabled,
)
from gsuite_activityevent.gsuite_workspace_password_enforce_strong_disabled import (
    g_suite_workspace_password_enforce_strong_disabled_tests as g_suite_workspace_password_enforce_strong_disabled_tests,
)
from gsuite_activityevent.gsuite_workspace_password_reuse_enabled import (
    GSuiteWorkspacePasswordReuseEnabled as GSuiteWorkspacePasswordReuseEnabled,
)
from gsuite_activityevent.gsuite_workspace_password_reuse_enabled import (
    g_suite_workspace_password_reuse_enabled_tests as g_suite_workspace_password_reuse_enabled_tests,
)
from gsuite_activityevent.gsuite_workspace_trusted_domains_allowlist import (
    GSuiteWorkspaceTrustedDomainsAllowlist as GSuiteWorkspaceTrustedDomainsAllowlist,
)
from gsuite_activityevent.gsuite_workspace_trusted_domains_allowlist import (
    g_suite_workspace_trusted_domains_allowlist_tests as g_suite_workspace_trusted_domains_allowlist_tests,
)
