from asana.asana_service_account_created import AsanaServiceAccountCreated as AsanaServiceAccountCreated
from asana.asana_service_account_created import (
    asana_service_account_created_tests as asana_service_account_created_tests,
)
from asana.asana_team_privacy_public import AsanaTeamPrivacyPublic as AsanaTeamPrivacyPublic
from asana.asana_team_privacy_public import asana_team_privacy_public_tests as asana_team_privacy_public_tests
from asana.asana_workspace_default_session_duration_never import (
    AsanaWorkspaceDefaultSessionDurationNever as AsanaWorkspaceDefaultSessionDurationNever,
)
from asana.asana_workspace_default_session_duration_never import (
    asana_workspace_default_session_duration_never_tests as asana_workspace_default_session_duration_never_tests,
)
from asana.asana_workspace_email_domain_added import AsanaWorkspaceEmailDomainAdded as AsanaWorkspaceEmailDomainAdded
from asana.asana_workspace_email_domain_added import (
    asana_workspace_email_domain_added_tests as asana_workspace_email_domain_added_tests,
)
from asana.asana_workspace_form_link_auth_requirement_disabled import (
    AsanaWorkspaceFormLinkAuthRequirementDisabled as AsanaWorkspaceFormLinkAuthRequirementDisabled,
)
from asana.asana_workspace_form_link_auth_requirement_disabled import (
    asana_workspace_form_link_auth_requirement_disabled_tests as asana_workspace_form_link_auth_requirement_disabled_tests,
)
from asana.asana_workspace_guest_invite_permissions_anyone import (
    AsanaWorkspaceGuestInvitePermissionsAnyone as AsanaWorkspaceGuestInvitePermissionsAnyone,
)
from asana.asana_workspace_guest_invite_permissions_anyone import (
    asana_workspace_guest_invite_permissions_anyone_tests as asana_workspace_guest_invite_permissions_anyone_tests,
)
from asana.asana_workspace_new_admin import AsanaWorkspaceNewAdmin as AsanaWorkspaceNewAdmin
from asana.asana_workspace_new_admin import asana_workspace_new_admin_tests as asana_workspace_new_admin_tests
from asana.asana_workspace_org_export import AsanaWorkspaceOrgExport as AsanaWorkspaceOrgExport
from asana.asana_workspace_org_export import asana_workspace_org_export_tests as asana_workspace_org_export_tests
from asana.asana_workspace_password_requirements_simple import (
    AsanaWorkspacePasswordRequirementsSimple as AsanaWorkspacePasswordRequirementsSimple,
)
from asana.asana_workspace_password_requirements_simple import (
    asana_workspace_password_requirements_simple_tests as asana_workspace_password_requirements_simple_tests,
)
from asana.asana_workspace_require_app_approvals_disabled import (
    AsanaWorkspaceRequireAppApprovalsDisabled as AsanaWorkspaceRequireAppApprovalsDisabled,
)
from asana.asana_workspace_require_app_approvals_disabled import (
    asana_workspace_require_app_approvals_disabled_tests as asana_workspace_require_app_approvals_disabled_tests,
)
from asana.asana_workspace_saml_optional import AsanaWorkspaceSAMLOptional as AsanaWorkspaceSAMLOptional
from asana.asana_workspace_saml_optional import (
    asana_workspace_saml_optional_tests as asana_workspace_saml_optional_tests,
)
