from gitlab.gitlab_audit_password_reset_multiple_emails import (
    GitLabAuditPasswordResetMultipleEmails as GitLabAuditPasswordResetMultipleEmails,
)
from gitlab.gitlab_audit_password_reset_multiple_emails import (
    git_lab_audit_password_reset_multiple_emails_tests as git_lab_audit_password_reset_multiple_emails_tests,
)
from gitlab.gitlab_production_password_reset_multiple_emails import (
    GitLabProductionPasswordResetMultipleEmails as GitLabProductionPasswordResetMultipleEmails,
)
from gitlab.gitlab_production_password_reset_multiple_emails import (
    git_lab_production_password_reset_multiple_emails_tests as git_lab_production_password_reset_multiple_emails_tests,
)
