from panther_audit.panther_detection_deleted import PantherDetectionDeleted as PantherDetectionDeleted
from panther_audit.panther_detection_deleted import panther_detection_deleted_tests as panther_detection_deleted_tests
from panther_audit.panther_saml_modified import PantherSAMLModified as PantherSAMLModified
from panther_audit.panther_saml_modified import panther_saml_modified_tests as panther_saml_modified_tests
from panther_audit.panther_sensitive_role_created import PantherSensitiveRole as PantherSensitiveRole
from panther_audit.panther_sensitive_role_created import panther_sensitive_role_tests as panther_sensitive_role_tests
from panther_audit.panther_user_modified import PantherUserModified as PantherUserModified
from panther_audit.panther_user_modified import panther_user_modified_tests as panther_user_modified_tests
