from github.github_action_failed import GitHubActionFailed as GitHubActionFailed
from github.github_action_failed import git_hub_action_failed_tests as git_hub_action_failed_tests
from github.github_advanced_security_change import GitHubAdvancedSecurityChange as GitHubAdvancedSecurityChange
from github.github_advanced_security_change import (
    git_hub_advanced_security_change_tests as git_hub_advanced_security_change_tests,
)
from github.github_branch_policy_override import GitHubBranchPolicyOverride as GitHubBranchPolicyOverride
from github.github_branch_policy_override import (
    git_hub_branch_policy_override_tests as git_hub_branch_policy_override_tests,
)
from github.github_branch_protection_disabled import GitHubBranchProtectionDisabled as GitHubBranchProtectionDisabled
from github.github_branch_protection_disabled import (
    git_hub_branch_protection_disabled_tests as git_hub_branch_protection_disabled_tests,
)
from github.github_org_auth_modified import GitHubOrgAuthChange as GitHubOrgAuthChange
from github.github_org_auth_modified import git_hub_org_auth_change_tests as git_hub_org_auth_change_tests
from github.github_org_ip_allowlist import GitHubOrgIpAllowlist as GitHubOrgIpAllowlist
from github.github_org_ip_allowlist import git_hub_org_ip_allowlist_tests as git_hub_org_ip_allowlist_tests
from github.github_org_moderators_add import GitHubOrgModeratorsAdd as GitHubOrgModeratorsAdd
from github.github_org_moderators_add import git_hub_org_moderators_add_tests as git_hub_org_moderators_add_tests
from github.github_org_modified import GitHubOrgModified as GitHubOrgModified
from github.github_org_modified import git_hub_org_modified_tests as git_hub_org_modified_tests
from github.github_organization_app_integration_installed import (
    GithubOrganizationAppIntegrationInstalled as GithubOrganizationAppIntegrationInstalled,
)
from github.github_organization_app_integration_installed import (
    github_organization_app_integration_installed_tests as github_organization_app_integration_installed_tests,
)
from github.github_public_repository_created import GithubPublicRepositoryCreated as GithubPublicRepositoryCreated
from github.github_public_repository_created import (
    github_public_repository_created_tests as github_public_repository_created_tests,
)
from github.github_repo_collaborator_change import GithubRepoCollaboratorChange as GithubRepoCollaboratorChange
from github.github_repo_collaborator_change import (
    github_repo_collaborator_change_tests as github_repo_collaborator_change_tests,
)
from github.github_repo_created import GithubRepoCreated as GithubRepoCreated
from github.github_repo_created import github_repo_created_tests as github_repo_created_tests
from github.github_repo_hook_modified import GitHubRepoHookModified as GitHubRepoHookModified
from github.github_repo_hook_modified import git_hub_repo_hook_modified_tests as git_hub_repo_hook_modified_tests
from github.github_repo_initial_access import GitHubRepoInitialAccess as GitHubRepoInitialAccess
from github.github_repo_initial_access import git_hub_repo_initial_access_tests as git_hub_repo_initial_access_tests
from github.github_repo_visibility_change import GithubRepoVisibilityChange as GithubRepoVisibilityChange
from github.github_repo_visibility_change import (
    github_repo_visibility_change_tests as github_repo_visibility_change_tests,
)
from github.github_repo_vulnerability_dismissed import (
    GithubRepoVulnerabilityDismissed as GithubRepoVulnerabilityDismissed,
)
from github.github_repo_vulnerability_dismissed import (
    github_repo_vulnerability_dismissed_tests as github_repo_vulnerability_dismissed_tests,
)
from github.github_repository_transfer import GithubRepositoryTransfer as GithubRepositoryTransfer
from github.github_repository_transfer import github_repository_transfer_tests as github_repository_transfer_tests
from github.github_secret_scanning_alert_created import (
    GitHubSecretScanningAlertCreated as GitHubSecretScanningAlertCreated,
)
from github.github_secret_scanning_alert_created import (
    git_hub_secret_scanning_alert_created_tests as git_hub_secret_scanning_alert_created_tests,
)
from github.github_team_modified import GitHubTeamModified as GitHubTeamModified
from github.github_team_modified import git_hub_team_modified_tests as git_hub_team_modified_tests
from github.github_user_access_key_created import GitHubUserAccessKeyCreated as GitHubUserAccessKeyCreated
from github.github_user_access_key_created import (
    git_hub_user_access_key_created_tests as git_hub_user_access_key_created_tests,
)
from github.github_user_role_updated import GitHubUserRoleUpdated as GitHubUserRoleUpdated
from github.github_user_role_updated import git_hub_user_role_updated_tests as git_hub_user_role_updated_tests
from github.github_webhook_modified import GitHubWebhookModified as GitHubWebhookModified
from github.github_webhook_modified import git_hub_webhook_modified_tests as git_hub_webhook_modified_tests
