from aws_securityfinding.decoy_dynamodb_accessed import DecoyDynamoDBAccessed as DecoyDynamoDBAccessed
from aws_securityfinding.decoy_dynamodb_accessed import decoy_dynamo_db_accessed_tests as decoy_dynamo_db_accessed_tests
from aws_securityfinding.decoy_iam_assumed import DecoyIAMAssumed as DecoyIAMAssumed
from aws_securityfinding.decoy_iam_assumed import decoy_iam_assumed_tests as decoy_iam_assumed_tests
from aws_securityfinding.decoy_s3_accessed import DecoyS3Accessed as DecoyS3Accessed
from aws_securityfinding.decoy_s3_accessed import decoy_s3_accessed_tests as decoy_s3_accessed_tests
from aws_securityfinding.decoy_secret_accessed import DecoySecretAccessed as DecoySecretAccessed
from aws_securityfinding.decoy_secret_accessed import decoy_secret_accessed_tests as decoy_secret_accessed_tests
from aws_securityfinding.decoy_systems_manager_parameter_accessed import (
    DecoySystemsManagerParameterAccessed as DecoySystemsManagerParameterAccessed,
)
from aws_securityfinding.decoy_systems_manager_parameter_accessed import (
    decoy_systems_manager_parameter_accessed_tests as decoy_systems_manager_parameter_accessed_tests,
)
