from zendesk.zendesk_mobile_app_access import ZendeskMobileAppAccessUpdated as ZendeskMobileAppAccessUpdated
from zendesk.zendesk_mobile_app_access import (
    zendesk_mobile_app_access_updated_tests as zendesk_mobile_app_access_updated_tests,
)
from zendesk.zendesk_new_api_token import ZendeskNewAPIToken as ZendeskNewAPIToken
from zendesk.zendesk_new_api_token import zendesk_new_api_token_tests as zendesk_new_api_token_tests
from zendesk.zendesk_new_owner import ZendeskAccountOwnerChanged as ZendeskAccountOwnerChanged
from zendesk.zendesk_new_owner import zendesk_account_owner_changed_tests as zendesk_account_owner_changed_tests
from zendesk.zendesk_sensitive_data_redaction import (
    ZendeskSensitiveDataRedactionOff as ZendeskSensitiveDataRedactionOff,
)
from zendesk.zendesk_sensitive_data_redaction import (
    zendesk_sensitive_data_redaction_off_tests as zendesk_sensitive_data_redaction_off_tests,
)
from zendesk.zendesk_user_assumption import ZendeskUserAssumption as ZendeskUserAssumption
from zendesk.zendesk_user_assumption import zendesk_user_assumption_tests as zendesk_user_assumption_tests
from zendesk.zendesk_user_role import ZendeskUserRoleChanged as ZendeskUserRoleChanged
from zendesk.zendesk_user_role import zendesk_user_role_changed_tests as zendesk_user_role_changed_tests
from zendesk.zendesk_user_suspension import ZendeskUserSuspension as ZendeskUserSuspension
from zendesk.zendesk_user_suspension import zendesk_user_suspension_tests as zendesk_user_suspension_tests
