name: Sync Panther-Analysis Release

on:
  workflow_dispatch:
    inputs:
      pa_branch:
        description: 'Panther-Analysis Branch to Sync'
        required: true
        default: 'main'

permissions:
  contents: write

jobs:
  sync-pa-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        token: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@5db1cf9a59fb97c40a68accab29236f0da7e94db
      with:
        python-version: '3.11'
    - name: Install Requirements
      run: |
        pip install --upgrade pip poetry
        poetry install
    - name: Download panther-analysis
      run: |
        git clone --branch ${{ github.event.inputs.pa_branch }} https://github.com/panther-labs/panther-analysis.git 
    - name: Run generate against panther-analysis
      # keeping this generate.py invocation as is for now in order to avoid possible complications with local
      # pypanther installation and versioning
      # this way we can also override the cwd_must_be_empty coarse safeguard we impose for external users
      run: |
        poetry run python ./pypanther/generate.py panther-analysis --keep-all-rules --verbose
    - name: Cleanup
      run: |
        rm -rf panther-analysis
    - name: fmt and lint
      run: |
        poetry run ruff check --fix .
        poetry run ruff format .
        poetry run ruff check --fix .
        poetry run ruff check --output-format=github .
        poetry run ruff format --check .
        poetry run mypy .
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # 6.3.0
      with:
        gpg_private_key: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Create PR
      env:
        GH_TOKEN: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
      run: |
        git config --global user.email "github-service-account-automation@panther.io"
        git config --global user.name "panther-bot-automation"  
        git add .
        git commit -a -m "sync panther-analysis release"
        git checkout -b sync-panther-analysis-release
        git push --set-upstream origin sync-panther-analysis-release
        gh pr create -t "Sync latest panther-analysis release" -b "Generated files from latest panther-analysis release."
