name: Sync Panther-Analysis Release

on:
  workflow_dispatch:
    inputs:
      pa_branch:
        description: 'Panther-Analysis Branch to Sync'
        required: true
        default: 'main'

permissions:
  contents: write

jobs:
  sync-pa-release:
    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit
    - name: Check out this repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
      with:
        python-version: '3.11'
    - name: Install Requirements
      run: |
        pip install --upgrade pip poetry
        poetry install
    - name: Download panther-analysis
      run: |
        git clone --branch ${{ github.event.inputs.pa_branch }} https://github.com/panther-labs/panther-analysis.git 
    - name: Run generate against panther-analysis
      # keeping this generate.py invocation as is for now in order to avoid possible complications with local
      # pypanther installation and versioning
      # this way we can also override the cwd_must_be_empty coarse safeguard we impose for external users
      run: |
        poetry run python ./pypanther/generate.py panther-analysis --keep-all-rules
    - name: Cleanup
      run: |
        rm -rf panther-analysis
    - name: fmt and lint
      run: |
        poetry run ruff check --fix .
        poetry run ruff format .
        poetry run ruff check --fix .
        poetry run ruff check --output-format=github .
        poetry run ruff format --check .
        poetry run mypy .
    - name: Create PR
      env:
        GH_TOKEN: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
      run: |
        git config user.name "dac-bot[bot]"
        git config user.email "dac-bot@panther.com"
        git add .
        git commit -a -m "sync panther-analysis release"
        git checkout -b sync-panther-analysis-release
        git push --set-upstream origin sync-panther-analysis-release
        gh pr create -t "Sync latest panther-analysis release" -b "Generated files from latest panther-analysis release."
