name: Tag with Latest Version on PR Merge

on:
  pull_request:
    types: [ closed ]

jobs:
  tag-on-merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.11'
      - name: Install Requirements
        run: |
          pip install --upgrade pip poetry
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # 6.3.0
        with:
          gpg_private_key: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Set up Git
        run: |
          git config --global user.email "github-service-account-automation@panther.io"
          git config --global user.name "panther-bot-automation"  
      - name: Check and update tag
        run: |
          VERSION="v$(poetry version --short)"
          
          if [[ $(git tag -l $VERSION) ]]; then
            echo "Tag $VERSION already exists"
          else
            echo "Tagging with $VERSION"
            git tag "$VERSION"
            git push origin --tags
          fi
