name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    name: Update version
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
      - uses: chainguard-dev/actions/setup-gitsign@e82b4e5ae10182af72972addcb3fedf7454621c8
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
        with:
          python-version: '3.11'
      - name: Install Requirements
        run: |
          pip install --upgrade pip poetry
      - name: Bump patch version
        run: poetry version prerelease
      #    - name: Tag the release
      #      run: |
      #        echo "Tagging v$(poetry version --short)"
      #        git tag "v$(poetry version --short)"
      #        git push --tags
      #        gitsign verify $(git rev-list --tags --max-count=1) --certificate-identity-regexp="https://github.com/${{ github.repository }}/*" --certificate-oidc-issuer="https://token.actions.githubusercontent.com"
      - name: Create Branch and Pull Request
        run: |
          NEW_VERSION="$(poetry version --short)"
          git config user.name "dac-bot[bot]"
          git config user.email "dac-bot@panther.com"
          git checkout -b "$NEW_VERSION"
          git commit -a -m "Bump version to $NEW_VERSION"
          git push --set-upstream origin "$NEW_VERSION"
          gh pr create -t "Version bump to v$NEW_VERSION" -b "Bumping Version to v$NEW_VERSION"
        env:
          GH_TOKEN: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
